services:
  - type: web
    name: seafood-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn transaction_api:app --host 0.0.0.0 --port 10000
